coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 5%
    patch:
      default:
        target: 60%
        threshold: 5%

ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/test/**"
  - "**/mock-*.ts"
  - "**/index.ts"
  - "**/*.config.*"
  - "**/*.d.ts"

